# src/main/resources/application.yml
server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: performance-tracker

  datasource:
    url: jdbc:postgresql://localhost:5433/sports_dev
    username: sports_user
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  #let Flyway manage schema
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        implicit_naming_stategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_stategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

# Simple CORS for the React App during dev
cors:
  allowed-origins: "https://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# JWT (wire this into Security config)
security:
  jwt:
    issuer: "sports-performance-tracker"
    secret: ${JWT_SECRET:change-me-dev-secret}
    access-token-ttl-min: 60
    refresh-token-ttl-days: 7

logging:
  level:
    root: INFO